#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name"
    echo "-v be verbose by using set -x"
    exit 1
}

while getopts v c
do
    case $c in
	v ) set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 2 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"

URL=https://pages.nist.gov/NIST-Tech-Pubs/NIST_Tech_Pubs_all.xlsx

./gen-bibxml-nist -v -c -X -u "$URL" -b "$TOPDIR/$BIBXMLNAME"
../bibxml_common/generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
