#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name 1id-abstracts.txt-url"
    echo "-v be verbose by using set -x"
    exit 1
}

while getopts v c
do
    case $c in
	v ) set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 3 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"
URL="$3"

./gen-bibxml-ids -v -B -u "$URL" -b "$TOPDIR/$BIBXMLNAME"
../bibxml_common/generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
