#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name"
    echo "-v be verbose by using set -x"
    exit 1
}

while getopts v c
do
    case $c in
	v ) set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 2 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"

URL=ftp://www.3gpp.org/Specs/html-info/2003-04-10_webexp11a_status-report_special_select.txt

./gen-bibxml-3gpp -v -u "$URL" -b "$TOPDIR/$BIBXMLNAME" -c
../bibxml_common/generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
