#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name cache-top-directory pswd-file-location"
    echo "-v be verbose by using set -x"
    exit 1
}

VERBOSE=false
while getopts v c
do
    case $c in
	v ) VERBOSE=true; set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 4 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"
CACHEDIR="$3"
PSWDFILE="$4"

set +x
if ! source "$PSWDFILE"
then
    ls -l "$PSWDFILE"
    echo "$0: Cannot read $PSWDFILE"
    exit 2
fi
$VERBOSE && set -x
export IEEEHOST IEEEUSER IEEEPSWD

DATE=$(date +%Y%m%d)
WEEKDAY=$(date +%A)

UPDATEDIR="$CACHEDIR"/updates."$DATE"

case "$WEEKDAY" in
    Monday | Thursday )
	if [ ! -d "$UPDATEDIR" ]
	then
	    # get the update from IEEE
	    # let the values used for logging in come from $PSWDFILE
	    # ./gen-bibxml-ieee-get-update -d "$UPDATEDIR" -H 'ftp.ieee.org' -U "$IEEEUSER" -P "$IEEEPSWD" &&
	    ./gen-bibxml-ieee-get-update -d "$UPDATEDIR" &&
	    # incorporate the update into the cache
	    ./gen-bibxml-ieee-apply-update -t -d "$UPDATEDIR" -i "$CACHEDIR"/cache &&
	    # create the bibxml files
	    ./gen-bibxml-ieee-gen-bibxml -v -b "$TOPDIR/$BIBXMLNAME" -i "$CACHEDIR"/cache/IEEEstd -x &&
	    # generate the tarball and zipfile
	    ../bibxml_common/generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
	else
	    echo "Skipping because $UPDATEDIR already exists"
	fi
	;;

    * )
	echo "Skipping because we only run on Monday and Thursday"
	;;
esac

