#!/bin/bash

set -u		# error on unset variables

PATH=$PATH:$PWD

DEFTOPDIR=/unknown
TOPDIR=$DEFTOPDIR
DEFBIBXML=bibxml
BIBXML=$DEFBIBXML
verbose=false

usage()
{
    exec 1>&2
    [ $# -gt 0 ] && echo "$@"
    echo "Usage: $0 [-t directory] [-1 bibxml-name]"
    echo " -t top level directory to run in, above bibxml directories, default $DEFTOPDIR"
    echo " -1 name of bibxml directory instead of default $DEFBIBXML"
    echo " -d path to rfc2629.dtd file, no default"
    echo " -v verbose"
    exit 1
}

DORDF=true
DOINDEXXML=true
DTDFILE=

while getopts 1:d:t:vRI c
do
    case "$c" in
	1 ) BIBXML="$OPTARG" ;;
	d ) DTDFILE="$OPTARG" ;;
	t ) TOPDIR="$OPTARG" ;;
	R ) DORDF=false ;;
	I ) DOINDEXXML=false ;;
	v ) verbose=:; set -x ;;
    ? ) usage ;;
    esac
done
shift $(($OPTIND - 1))

# make sure bibxml is a simple name
case "$BIBXML" in
    */* ) usage "name of bibxml directory may not be a path: '$BIBXML'"
esac

# within the current directory
cd $TOPDIR || usage "Cannot cd $TOPDIR"


# create the bibxml directory:
mkdir -p "$BIBXML" || usage "Cannot mkdir $BIBXML"
[ -d "$BIBXML" ] || usage "Could not mkdir $BIBXML."

TMP1=$(mktemp --suffix=t1)
TMP2=$(mktemp --suffix=t2)
TMP3=$(mktemp --suffix=t3)
trap 'rm -f $TMP1 $TMP2 $TMP3' 0 1 2 3 15

# minor error if these are split on a time boundary
DAY=`date +%d`
MONTH=`date +%B`
YEAR=`date +%Y`

################################################################
# for each RFC, generate reference.RFC.####.xml
# (do this by rsyncing against rfc-editor.org)
################################################################

# rsync --times --compress --log-file=$TMP3 --log-file-format="%n" ftp.rfc-editor.org::refs bibxml > $TMP1 2> $TMP2
rsync -az --log-file=$TMP3 --log-file-format="%n" ftp.rfc-editor.org::refs $BIBXML > $TMP1 2> $TMP2
$verbose && head -1000 $TMP1 $TMP2 $TMP3


################################################################
# create index.xml
################################################################

$DOINDEXXML && mkBibxmlIndexXml $BIBXML

################################################################
# create $BIBXML/rdf/index.RFC.*.rdf
# If $BIBXML/rdf/index.RFC.FOO.rdf does not exist or is older than $BIBXML/reference.RFC.FOO.xml, create the RDF from the xml
################################################################

$DORDF && mkBibxmlRdfFiles $BIBXML

################################################################
# for each RFC file that was new, create index.rdf
################################################################

mkBibxmlIndexRdf $BIBXML $TMP3

################################################################
# update the DTD, ZIP and TGZ files
################################################################

# update rfc2629.dtd
[ -n "$DTDFILE" -a "$DTDFILE" -nt "$BIBXML/rfc2629.dtd" ] &&
    cp -p "$DTDFILE" "$BIBXML/rfc2629.dtd"

mkBibxmlZipTgz $BIBXML
