#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name rfc-index-url"
    echo "-v be verbose by using set -x"
    exit 1
}

while getopts v c
do
    case $c in
	v ) set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 3 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"
RFCINDEXURL="$3"

./gen-bibxml-rfcs-via-rsync -t "$TOPDIR" -1 "$BIBXMLNAME"
generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
