# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/preferences.ui'
#
# Created: Fri Aug 19 18:16:06 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 350)
        Dialog.setMinimumSize(QtCore.QSize(500, 350))
        Dialog.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.conversionTab = QtGui.QWidget()
        self.conversionTab.setObjectName(_fromUtf8("conversionTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.conversionTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_5 = QtGui.QGroupBox(self.conversionTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setContentsMargins(12, 12, 12, -1)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.outputDir = QtGui.QLineEdit(self.groupBox_5)
        self.outputDir.setObjectName(_fromUtf8("outputDir"))
        self.gridLayout.addWidget(self.outputDir, 1, 0, 1, 1)
        self.outputClear = QtGui.QPushButton(self.groupBox_5)
        self.outputClear.setObjectName(_fromUtf8("outputClear"))
        self.gridLayout.addWidget(self.outputClear, 1, 2, 1, 1)
        self.outputBrowse = QtGui.QPushButton(self.groupBox_5)
        self.outputBrowse.setObjectName(_fromUtf8("outputBrowse"))
        self.gridLayout.addWidget(self.outputBrowse, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.tabWidget.addTab(self.conversionTab, _fromUtf8(""))
        self.appearanceTab = QtGui.QWidget()
        self.appearanceTab.setObjectName(_fromUtf8("appearanceTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.appearanceTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.appearanceTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.previewFontButton = QtGui.QPushButton(self.groupBox)
        self.previewFontButton.setObjectName(_fromUtf8("previewFontButton"))
        self.verticalLayout_3.addWidget(self.previewFontButton)
        self.previewLineNumbersXml = QtGui.QCheckBox(self.groupBox)
        self.previewLineNumbersXml.setChecked(True)
        self.previewLineNumbersXml.setObjectName(_fromUtf8("previewLineNumbersXml"))
        self.verticalLayout_3.addWidget(self.previewLineNumbersXml)
        self.previewLineNumbersText = QtGui.QCheckBox(self.groupBox)
        self.previewLineNumbersText.setObjectName(_fromUtf8("previewLineNumbersText"))
        self.verticalLayout_3.addWidget(self.previewLineNumbersText)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.appearanceTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.consoleFontButton = QtGui.QPushButton(self.groupBox_2)
        self.consoleFontButton.setObjectName(_fromUtf8("consoleFontButton"))
        self.verticalLayout_4.addWidget(self.consoleFontButton)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.appearanceTab, _fromUtf8(""))
        self.cacheTab = QtGui.QWidget()
        self.cacheTab.setObjectName(_fromUtf8("cacheTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.cacheTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.cacheTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setMargin(0)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.cacheLocationDesc = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacheLocationDesc.sizePolicy().hasHeightForWidth())
        self.cacheLocationDesc.setSizePolicy(sizePolicy)
        self.cacheLocationDesc.setObjectName(_fromUtf8("cacheLocationDesc"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.cacheLocationDesc)
        self.cacheLocationText = QtGui.QLabel(self.widget)
        self.cacheLocationText.setText(_fromUtf8(""))
        self.cacheLocationText.setObjectName(_fromUtf8("cacheLocationText"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cacheLocationText)
        self.verticalLayout_6.addWidget(self.widget)
        self.widget_3 = QtGui.QWidget(self.groupBox_3)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cacheBrowseButton = QtGui.QPushButton(self.widget_3)
        self.cacheBrowseButton.setObjectName(_fromUtf8("cacheBrowseButton"))
        self.horizontalLayout.addWidget(self.cacheBrowseButton)
        self.cacheResetButton = QtGui.QPushButton(self.widget_3)
        self.cacheResetButton.setObjectName(_fromUtf8("cacheResetButton"))
        self.horizontalLayout.addWidget(self.cacheResetButton)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.cacheTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_2 = QtGui.QWidget(self.groupBox_4)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.widget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.cacheSizeDes = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cacheSizeDes.sizePolicy().hasHeightForWidth())
        self.cacheSizeDes.setSizePolicy(sizePolicy)
        self.cacheSizeDes.setObjectName(_fromUtf8("cacheSizeDes"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.cacheSizeDes)
        self.cacheSizeLabel = QtGui.QLabel(self.widget_2)
        self.cacheSizeLabel.setObjectName(_fromUtf8("cacheSizeLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cacheSizeLabel)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.cacheDeleteButton = QtGui.QPushButton(self.groupBox_4)
        self.cacheDeleteButton.setEnabled(True)
        self.cacheDeleteButton.setObjectName(_fromUtf8("cacheDeleteButton"))
        self.verticalLayout_7.addWidget(self.cacheDeleteButton)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.cacheTab, _fromUtf8(""))
        self.libraryTab = QtGui.QWidget()
        self.libraryTab.setObjectName(_fromUtf8("libraryTab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.libraryTab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_6 = QtGui.QGroupBox(self.libraryTab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.localLibraryLabel = QtGui.QLabel(self.groupBox_6)
        self.localLibraryLabel.setObjectName(_fromUtf8("localLibraryLabel"))
        self.verticalLayout_9.addWidget(self.localLibraryLabel)
        self.localLibraries = QtGui.QLineEdit(self.groupBox_6)
        self.localLibraries.setObjectName(_fromUtf8("localLibraries"))
        self.verticalLayout_9.addWidget(self.localLibraries)
        self.widget_5 = QtGui.QWidget(self.groupBox_6)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.libraryBrowseButton = QtGui.QPushButton(self.widget_5)
        self.libraryBrowseButton.setObjectName(_fromUtf8("libraryBrowseButton"))
        self.horizontalLayout_2.addWidget(self.libraryBrowseButton)
        self.libraryResetButton = QtGui.QPushButton(self.widget_5)
        self.libraryResetButton.setObjectName(_fromUtf8("libraryResetButton"))
        self.horizontalLayout_2.addWidget(self.libraryResetButton)
        self.verticalLayout_9.addWidget(self.widget_5)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.libraryTab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.networkLibrary = QtGui.QLineEdit(self.groupBox_7)
        self.networkLibrary.setText(_fromUtf8(""))
        self.networkLibrary.setObjectName(_fromUtf8("networkLibrary"))
        self.gridLayout_2.addWidget(self.networkLibrary, 0, 1, 1, 1)
        self.networkLibraryResetButton = QtGui.QPushButton(self.groupBox_7)
        self.networkLibraryResetButton.setObjectName(_fromUtf8("networkLibraryResetButton"))
        self.gridLayout_2.addWidget(self.networkLibraryResetButton, 0, 2, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.libraryTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Document output", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Output directory (defaults to input directory if none is set)", None, QtGui.QApplication.UnicodeUTF8))
        self.outputClear.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.outputBrowse.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conversionTab), QtGui.QApplication.translate("Dialog", "Conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Document text", None, QtGui.QApplication.UnicodeUTF8))
        self.previewFontButton.setText(QtGui.QApplication.translate("Dialog", "Change Font", None, QtGui.QApplication.UnicodeUTF8))
        self.previewLineNumbersXml.setText(QtGui.QApplication.translate("Dialog", "Show line numbers for XML documents", None, QtGui.QApplication.UnicodeUTF8))
        self.previewLineNumbersText.setText(QtGui.QApplication.translate("Dialog", "Show line numbers for text documents", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Console text", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleFontButton.setText(QtGui.QApplication.translate("Dialog", "Change Font", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearanceTab), QtGui.QApplication.translate("Dialog", "Appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Cache directory", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheLocationDesc.setText(QtGui.QApplication.translate("Dialog", "Location: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheBrowseButton.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheResetButton.setText(QtGui.QApplication.translate("Dialog", "Reset location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Cache data", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheSizeDes.setText(QtGui.QApplication.translate("Dialog", "Size: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheSizeLabel.setText(QtGui.QApplication.translate("Dialog", "0 KB", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheDeleteButton.setText(QtGui.QApplication.translate("Dialog", "Delete cache", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cacheTab), QtGui.QApplication.translate("Dialog", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Local citation libraries", None, QtGui.QApplication.UnicodeUTF8))
        self.localLibraryLabel.setText(QtGui.QApplication.translate("Dialog", "Locations (separated by colons)", None, QtGui.QApplication.UnicodeUTF8))
        self.libraryBrowseButton.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.libraryResetButton.setText(QtGui.QApplication.translate("Dialog", "Reset locations", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog", "Network citation library", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.networkLibraryResetButton.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.libraryTab), QtGui.QApplication.translate("Dialog", "References", None, QtGui.QApplication.UnicodeUTF8))

