# do not edit this file

# server-specific
package ifneeded beepcore::server 1.0 \
        [list source [file join $dir beep-server.tcl]]
package ifneeded beepcore::sasl  1.0 \
        [list source [file join $dir beep-sasl.tcl]]

# client-specific
package ifneeded beepcore::client 1.0 \
        [list source [file join $dir beep-client.tcl]]
package ifneeded beepcore::mixer 1.0 \
        [list source [file join $dir beep-client.tcl]]

# server-profiles
package ifneeded beepcore::profile::anonymous 1.0 \
        [list source [file join $dir profile-anonymous.tcl]]
package ifneeded beepcore::profile::authmgmt 1.0 \
        [list source [file join $dir profile-authmgmt.tcl]]
package ifneeded beepcore::profile::external 1.0 \
        [list source [file join $dir profile-external.tcl]]
package ifneeded beepcore::profile::null 1.0 \
        [list source [file join $dir profile-null.tcl]]
package ifneeded beepcore::profile::otp 1.0 \
        [list source [file join $dir profile-otp.tcl]]
package ifneeded beepcore::profile::sudsy 1.0 \
        [list source [file join $dir profile-sudsy.tcl]]
package ifneeded beepcore::profile::syslog-raw 1.0 \
        [list source [file join $dir profile-syslog-raw.tcl]]
package ifneeded beepcore::profile::tlsv1 1.0 \
        [list source [file join $dir profile-tlsv1.tcl]]
package ifneeded beepcore::profile::tunnel 1.0 \
        [list source [file join $dir profile-tunnel.tcl]]

# generic
package ifneeded beepcore::log   1.0 \
        [list source [file join $dir beep-logging.tcl]]
package ifneeded beepcore::peer  1.0 \
        [list source [file join $dir beep-peer.tcl]]
package ifneeded beepcore::util  1.0 \
        [list source [file join $dir beep-utilities.tcl]]

