#!/bin/bash

usage()
{
    exec 1>&2
    echo "Usage: $0 [-v] bibxml-top-directory bibxml-name"
    echo "-v be verbose by using set -x"
    exit 1
}

while getopts v c
do
    case $c in
	v ) set -x ;;
	? ) usage ;;
    esac
done
shift $(( OPTIND - 1))

[ $# -eq 2 ] || usage

TOPDIR="$1"
BIBXMLNAME="$2"

URL=https://www.w3.org/2002/01/tr-automation/tr.rdf

./gen-bibxml-w3c -v -c -u "$URL" -b "$TOPDIR/$BIBXMLNAME"
../bibxml_common/generate-tarball-zipfile "$TOPDIR" "$BIBXMLNAME"
