trang.jar:	trang-20091111.zip
	unzip -j trang-20091111.zip trang-20091111/trang.jar


trang-20091111.zip:
	wget http://jing-trang.googlecode.com/files/trang-20091111.zip || \
	curl -o trang-20091111.zip http://jing-trang.googlecode.com/files/trang-20091111.zip
